In [1]:
!pip install numpy   # install numpy 

In [2]:
import numpy as np

In [5]:
a = np.arange(9) #
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [6]:
a.shape


(9,)

In [9]:
aa =a[np.newaxis , :] # print(a[1:])
aa.shape

(1, 9)

In [11]:
arush = np.array([1,2,3]) # 1 x 3
arush

array([1, 2, 3])

In [14]:
arush.shape


(3,)

In [ ]:
#Numpy Array Operation and Declaration

In [16]:
star = np.array([[1,2,3],[4,5,6]]) # 2 x 3
star

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
amit = np.array([[1,2,3],[4,5,6],[7,8,9]])  # 3 x 3
amit

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [50]:
amit.size

9

In [22]:
print(amit[0][2]) # accessing specific element

3


In [ ]:
print(amit[0])# accessing specific row 

In [24]:
np.zeros(9) # creating array with multiple zeros element 

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [28]:
np.zeros_like(amit)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [29]:
np.ones(3)

array([1., 1., 1.])

In [31]:
np.empty(5) # random value based on state and memory

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [32]:
np.arange(1, 11, 2)

array([1, 3, 5, 7, 9])

In [34]:
np.arange(2, 20 , 3)

array([ 2,  5,  8, 11, 14, 17])

In [36]:
np.linspace(1, 15, num=10)

array([ 1.        ,  2.55555556,  4.11111111,  5.66666667,  7.22222222,
        8.77777778, 10.33333333, 11.88888889, 13.44444444, 15.        ])

In [41]:
np.ones(10,dtype=np.int64)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [44]:
hack = np.array([10,8,6,4,2,12,34,56,7,8,92,39])

In [45]:
np.sort(hack)

array([ 2,  4,  6,  7,  8,  8, 10, 12, 34, 39, 56, 92])

In [46]:
c = np.array([1,2,3])
d = np.array([6,8,9])
e = np.concatenate((c,d))
print(e)

[1 2 3 6 8 9]


In [49]:
amit.ndim

2

In [48]:
e.ndim

1

In [51]:
hack.reshape(3,4)

array([[10,  8,  6,  4],
       [ 2, 12, 34, 56],
       [ 7,  8, 92, 39]])

In [52]:
hack

array([10,  8,  6,  4,  2, 12, 34, 56,  7,  8, 92, 39])

In [53]:
hack[1]


8

In [54]:
hack[0:]

array([10,  8,  6,  4,  2, 12, 34, 56,  7,  8, 92, 39])

In [56]:
hack[:-1]

array([10,  8,  6,  4,  2, 12, 34, 56,  7,  8, 92])

In [62]:
hack[3:5]

array([4, 2])

In [61]:
hack[3:10]

array([ 4,  2, 12, 34, 56,  7,  8])

In [59]:
hack[-7:]

array([12, 34, 56,  7,  8, 92, 39])

In [63]:
print(hack[hack % 2 == 0])

[10  8  6  4  2 12 34 56  8 92]


In [64]:
print(hack[hack > 5])

[10  8  6 12 34 56  7  8 92 39]


In [65]:
print(hack[hack < 5])


[4 2]


In [71]:
print(hack[(hack > 10) | (hack >15)])  # Or operator | , & and operator is representing with

[12 34 56 92 39]
